# Generated by Django 5.1.3 on 2024-11-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='grade',
            field=models.CharField(choices=[], default='01', max_length=2, verbose_name='position grade'),
        ),
        migrations.AlterField(
            model_name='position',
            name='series',
            field=models.CharField(choices=[], default='A', max_length=1, verbose_name='position series'),
        ),
    ]
