# Generated by Django 5.1.3 on 2024-11-27 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('syscfg', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateField(blank=True, null=True, verbose_name='begin date')),
                ('end', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('creator', models.CharField(blank=True, max_length=20, null=True, verbose_name='creator')),
                ('modifier', models.CharField(blank=True, max_length=20, null=True, verbose_name='modifier')),
                ('creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='creation')),
                ('modification', models.DateTimeField(auto_now=True, null=True, verbose_name='modification')),
                ('code', models.CharField(blank=True, max_length=6, null=True, verbose_name='list code')),
                ('name', models.CharField(max_length=40, verbose_name='list name')),
                ('status', models.BooleanField(default=True, verbose_name='in use')),
                ('init', models.BooleanField(default=False, verbose_name='is init')),
                ('locked', models.BooleanField(default=False, verbose_name='is locked')),
                ('lock_time', models.DateTimeField(blank=True, null=True, verbose_name='locked time')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='locked by')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='syscfg.module', verbose_name='module')),
            ],
            options={
                'verbose_name': 'value list',
                'verbose_name_plural': 'value list',
            },
        ),
        migrations.CreateModel(
            name='ValueListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.CharField(blank=True, max_length=6, null=True)),
                ('code', models.CharField(blank=True, max_length=6, null=True, verbose_name='item code')),
                ('name', models.CharField(max_length=40, verbose_name='item name')),
                ('status', models.BooleanField(default=True, verbose_name='in use')),
                ('weight', models.IntegerField(default=9, null=True, verbose_name='weight')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.valuelist', verbose_name='list group')),
            ],
            options={
                'verbose_name': 'list item',
                'verbose_name_plural': 'list item',
                'ordering': ['weight', 'code'],
                'indexes': [models.Index(fields=['group', 'group_code'], name='basedata_va_group_i_83f7f5_idx')],
            },
        ),
    ]
