# Generated by Django 5.1.3 on 2024-11-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0003_alter_address_address_type_alter_dataimport_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('0', 'Unknown gender'), ('1', 'male'), ('2', 'female'), ('9', 'Unspecified gender')], default='1', max_length=100, verbose_name='gender'),
        ),
    ]
