# Generated by Django 5.1.3 on 2024-11-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialinventory',
            name='status',
            field=models.CharField(choices=[('0', 'NEW'), ('9', 'EXECUTED')], default='0', max_length=100, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='inoutdetail',
            name='prop',
            field=models.CharField(choices=[('+', 'PLUS'), ('-', 'MINUS')], default='+', max_length=100, verbose_name='plus or minus property'),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='status',
            field=models.CharField(choices=[('0', 'NEW'), ('1', 'QUALITY TESTING'), ('9', 'EXECUTED')], default='0', max_length=100, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='status',
            field=models.CharField(choices=[('0', 'NEW'), ('1', 'IN PROGRESS'), ('9', 'EXECUTED')], default='0', max_length=100, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='wareadjust',
            name='status',
            field=models.CharField(choices=[('0', 'NEW'), ('1', 'IN PROGRESS'), ('9', 'EXECUTED')], default='0', max_length=100, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='warereturn',
            name='status',
            field=models.CharField(choices=[('0', 'NEW'), ('1', 'IN PROGRESS'), ('9', 'EXECUTED')], default='0', max_length=100, verbose_name='status'),
        ),
    ]
