# Generated by Django 5.1.3 on 2024-11-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeritem',
            name='tax',
            field=models.CharField(choices=[('0.00', '0%'), ('0.03', '3%'), ('0.05', '5%'), ('0.07', '7%'), ('0.10', '10%'), ('0.17', '17%')], default='0.00', max_length=6, verbose_name='tax rate'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='tax',
            field=models.CharField(choices=[('0.00', '0%'), ('0.03', '3%'), ('0.05', '5%'), ('0.07', '7%'), ('0.10', '10%'), ('0.17', '17%')], default='0.00', max_length=6, verbose_name='tax rate'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='invoice_type',
            field=models.CharField(choices=[('10', '普通发票'), ('20', '增值税专用发票'), ('30', '专业发票')], default='10', max_length=6, verbose_name='invoice type'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='status',
            field=models.CharField(choices=[('0', 'NEW'), ('1', 'IN PROGRESS'), ('4', 'DROP'), ('9', 'APPROVED'), ('99', 'ALREADY STOCK OUT')], default='0', max_length=100, verbose_name='status'),
        ),
    ]
